# Generated by Django 5.1 on 2024-08-08 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_remove_adoption_adopted_at_adoption_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_adoptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
