# Generated by Django 5.1 on 2024-08-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0005_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='status',
            field=models.CharField(choices=[('adopted', 'Adoptado'), ('pending_adoption', 'En Proceso')], default='pending_adoption', max_length=20),
        ),
    ]
